### ISSUE TITLE
Add easy way to replace entire structure

### ISSUE THREAD

**Issue by ZebulanStanphill** [baron816/use-structure#2]
I ran into a situation where I needed to replace the entire contents of an array... or perhaps more accurately, replace the array with a new one. I quickly realized that there was no obvious way to do this.

First I tried the obvious approach one would take in vanilla JS:

```js
let myArray = useStructure(initialData)

function someFunction() {
	myArray = ['donut', 'cake']
}
```

Of course, this didn't work because the new array wasn't using a Proxy. I later discovered another approach using `Array.prototype.splice`:

```js
const myArray = useStructure(initialData)

function someFunction() {
	myArray.splice(0, myArray.length, ...['donut', 'cake'])
}
```

This works, but it feels rather convoluted and unintuitive, even compared to what `useState` lets you do:

```js
const [myArray, setMyArray] = useState(initialData)

function someFunction() {
	setMyArray(['donut', 'cake'])
}
```

This is a little ironic since the whole point of this package is to make working with structures easier. Of course, every approach has its own trade-offs, but I wonder if we can at least smooth this one out a bit.

Here's the first idea that came to mind: what if `useStructure` returned a set/replace callback along with the proxied structure?

```js
const [myArray, setMyArray] = useStructure(initialData)

// Of course, you can choose to only destructure the proxied structure if you don't need to replace it.
// const [myArray] = useStructure(initialData)

// Mutating the array still works, of course.
myArray.push('fries')

// But if you want to replace the contents, you now have an obvious way to do it.
setMyArray(['donut', 'cake'])
```

What do you think?

**Comment by baron816** [comment]
@ZebulanStanphill Thanks for the issue. First one here. I appreciate you taking this for a spin.

I don't want the API to be different from what's in the JS spec. I don't want there to be anything to "learn" here--you use it as if you were using Javascript.

Also, the reason it wasn't working in your naive approach was that you were reassigning the variable instead of "mutating" the object, and doing that doesn't keep that new value into the next render.

What I recommend in your case is to wrap your array in an object. Then you can set that object value to an empty array when you need to:
```javascript
const state = useStructure({ myArray: initialData });

function handleNewArr() {
   state.myArray = ['donut', 'cake'];
}
```

**Comment by ZebulanStanphill** [comment]
>I don't want the API to be different from what's in the JS spec. I don't want there to be anything to "learn" here--you use it as if you were using Javascript.

Arguably, being unable to do `myArray = newValue` is already going against the normal JS way of doing things, but I suppose introducing `setXXX` functions isn't much better. And I guess the usage of `const` with all(?) React hooks already implies that reassignment is a no-no.

I'd gotten so used to the usual hooks way of having all state be separate that I hadn't even considered using a state object to hold other values. But that's probably a more reasonable solution than what I was suggesting... perhaps even the best solution possible in React. Thanks for pointing that out. At the moment, it feels like a step backward to go back to using a single state object, but like I said earlier: everything has its tradeoffs.

Again, thanks. This is certainly the best alternative to `useState` I've seen in the React world.

On a side note, I think you might find [Crank](https://crank.js.org/) interesting. I discovered it yesterday while looking for alternatives to the standard React and Vue ways of handling component state. It's pretty much as close to pure JS variable manipulation as one can get, though I'm not yet sure how I feel about its own tradeoffs (particularly the explicit `this.refresh()` compared to React and Vue's automatic rerendering). It's definitely worth checking out, if only to get a new perspective on how UI libraries could be implemented by taking advantage of generators.
